site_name: Runaterra-Docs

pages:
    - 'Home': 'index.md'
    - 'Architecture' : 'Architecture.md'
    - 'Hosting and Deployment' : 'Hosting-and-Deployment.md'
    - 'Initial Setup' : 'Initial-Setup.md'
    - 'Standards and guidelines' : 'Standards-and-Guidelines.md'
    - 'Services' :
        - 'Ekko (Dashboard)' : 'Ekko(Dashboard)/'
        - 'Taric (Human Resources)' : 'Taric(HR)/'

